export const dataDestination = [
  {
    id: 1,
    airportCode: 'VKO',
    timezone: 'GMT +3',
    countryName: 'Россия',
    cityName: 'Москва',
    airportName: 'Внуково',
  },
  {
    id: 2,
    airportCode: 'VOG',
    timezone: 'GMT +3',
    countryName: 'Россия',
    cityName: 'Волгоград',
    airportName: 'Гумрак',
  },
  {
    id: 3,
    airportCode: 'MQF',
    timezone: 'GMT +5',
    countryName: 'Россия',
    cityName: 'Магнитогорск',
    airportName: 'Магнитогорск',
  },
  {
    id: 4,
    airportCode: 'OMS',
    timezone: 'GMT +6',
    countryName: 'Россия',
    cityName: 'Омск',
    airportName: 'Омск',
  },
  {
    id: 5,
    airportCode: 'VOZ',
    timezone: 'GMT +3',
    countryName: 'Россия',
    cityName: 'Воронеж',
    airportName: 'Чертовицкое',
  },
  {
    id: 6,
    airportCode: 'SVX',
    timezone: 'GMT +5',
    countryName: 'Россия',
    cityName: 'Екатеринбург',
    airportName: 'Кольцово',
  },
  {
    id: 7,
    airportCode: 'AAQ',
    timezone: 'GMT +3',
    countryName: 'Россия',
    cityName: 'Анапа',
    airportName: 'Витязево',
  },
  {
    id: 8,
    airportCode: 'ARH',
    timezone: 'GMT +3',
    countryName: 'Россия',
    cityName: 'Архангельск',
    airportName: 'Талаги',
  },
  {
    id: 9,
    airportCode: 'ARH',
    timezone: 'GMT +3',
    countryName: 'Россия',
    cityName: 'Архангельск',
    airportName: 'Талаги',
  },
  {
    id: 10,
    airportCode: 'ARH',
    timezone: 'GMT +3',
    countryName: 'Россия',
    cityName: 'Архангельск',
    airportName: 'Талаги',
  },
];
