export const dataSeatingArrangements = [
  {
    id: 1,
    fare: 999,
    isRegistered: true,
    isSold: true,
    isBooked: true,
    flightId: 5674,
    seat: {
      id: 5674,
      seatNumber: 'string',
      isNearEmergencyExit: true,
      isLockedBack: true,
      category: 'FIRST',
      aircraftId: 0,
    },
  },
  {
    id: 2,
    fare: 999,
    isRegistered: true,
    isSold: false,
    isBooked: true,
    flightId: 7685,
    seat: {
      id: 7685,
      seatNumber: 'string',
      isNearEmergencyExit: true,
      isLockedBack: true,
      category: 'ECONOMY',
      aircraftId: 0,
    },
  },
  {
    id: 3,
    fare: 999,
    isRegistered: true,
    isSold: true,
    isBooked: false,
    flightId: 765,
    seat: {
      id: 7654,
      seatNumber: 'string',
      isNearEmergencyExit: true,
      isLockedBack: true,
      category: 'PREMIUM_ECONOMY',
      aircraftId: 0,
    },
  },
  {
    id: 4,
    fare: 9897,
    isRegistered: true,
    isSold: false,
    isBooked: false,
    flightId: 9876,
    seat: {
      id: 9876,
      seatNumber: 'string',
      isNearEmergencyExit: true,
      isLockedBack: true,
      category: 'BUSINESS',
      aircraftId: 0,
    },
  },
  {
    id: 5,
    fare: 689,
    isRegistered: false,
    isSold: true,
    isBooked: true,
    flightId: 1112,
    seat: {
      id: 1112,
      seatNumber: 'string',
      isNearEmergencyExit: true,
      isLockedBack: true,
      category: 'FIRST',
      aircraftId: 0,
    },
  },
  {
    id: 6,
    fare: 898,
    isRegistered: false,
    isSold: true,
    isBooked: false,
    flightId: 7756,
    seat: {
      id: 7756,
      seatNumber: 'string',
      isNearEmergencyExit: true,
      isLockedBack: true,
      category: 'ECONOMY',
      aircraftId: 0,
    },
  },
  {
    id: 7,
    fare: 787,
    isRegistered: true,
    isSold: true,
    isBooked: true,
    flightId: 8989,
    seat: {
      id: 8989,
      seatNumber: 'string',
      isNearEmergencyExit: true,
      isLockedBack: true,
      category: 'FIRST',
      aircraftId: 0,
    },
  },
  {
    id: 8,
    fare: 777,
    isRegistered: true,
    isSold: true,
    isBooked: true,
    flightId: 1323,
    seat: {
      id: 1323,
      seatNumber: 'string',
      isNearEmergencyExit: true,
      isLockedBack: true,
      category: 'FIRST',
      aircraftId: 0,
    },
  },
  {
    id: 9,
    fare: 8697,
    isRegistered: false,
    isSold: false,
    isBooked: false,
    flightId: 9944,
    seat: {
      id: 9944,
      seatNumber: 'string',
      isNearEmergencyExit: true,
      isLockedBack: true,
      category: 'BUSINESS',
      aircraftId: 0,
    },
  },
  {
    id: 10,
    fare: 4657,
    isRegistered: true,
    isSold: true,
    isBooked: true,
    flightId: 4545,
    seat: {
      id: 4545,
      seatNumber: 'string',
      isNearEmergencyExit: true,
      isLockedBack: true,
      category: 'PREMIUM_ECONOMY',
      aircraftId: 0,
    },
  },
  {
    id: 11,
    fare: 899,
    isRegistered: true,
    isSold: true,
    isBooked: true,
    flightId: 1000,
    seat: {
      id: 1000,
      seatNumber: 'string',
      isNearEmergencyExit: true,
      isLockedBack: true,
      category: 'FIRST',
      aircraftId: 0,
    },
  },
  {
    id: 12,
    fare: 987,
    isRegistered: true,
    isSold: true,
    isBooked: false,
    flightId: 7666,
    seat: {
      id: 7666,
      seatNumber: 'string',
      isNearEmergencyExit: true,
      isLockedBack: true,
      category: 'ECONOMY',
      aircraftId: 0,
    },
  },
  {
    id: 13,
    fare: 999,
    isRegistered: true,
    isSold: true,
    isBooked: true,
    flightId: 6566,
    seat: {
      id: 6566,
      seatNumber: 'string',
      isNearEmergencyExit: true,
      isLockedBack: true,
      category: 'FIRST',
      aircraftId: 0,
    },
  },
  {
    id: 14,
    fare: 999,
    isRegistered: false,
    isSold: true,
    isBooked: true,
    flightId: 7777,
    seat: {
      id: 7777,
      seatNumber: 'string',
      isNearEmergencyExit: true,
      isLockedBack: true,
      category: 'ECONOMY',
      aircraftId: 0,
    },
  },
  {
    id: 15,
    fare: 999,
    isRegistered: true,
    isSold: true,
    isBooked: false,
    flightId: 5143,
    seat: {
      id: 5143,
      seatNumber: 'string',
      isNearEmergencyExit: true,
      isLockedBack: true,
      category: 'BUSINESS',
      aircraftId: 0,
    },
  },
  {
    id: 16,
    fare: 999,
    isRegistered: true,
    isSold: true,
    isBooked: true,
    flightId: 9008,
    seat: {
      id: 9008,
      seatNumber: 'string',
      isNearEmergencyExit: true,
      isLockedBack: true,
      category: 'FIRST',
      aircraftId: 0,
    },
  },
  {
    id: 17,
    fare: 999,
    isRegistered: true,
    isSold: true,
    isBooked: true,
    flightId: 3214,
    seat: {
      id: 3214,
      seatNumber: 'string',
      isNearEmergencyExit: true,
      isLockedBack: true,
      category: 'BUSINESS',
      aircraftId: 0,
    },
  },
  {
    id: 18,
    fare: 999,
    isRegistered: false,
    isSold: false,
    isBooked: true,
    flightId: 5231,
    seat: {
      id: 5231,
      seatNumber: 'string',
      isNearEmergencyExit: true,
      isLockedBack: true,
      category: 'FIRST',
      aircraftId: 0,
    },
  },
  {
    id: 19,
    fare: 999,
    isRegistered: true,
    isSold: true,
    isBooked: true,
    flightId: 2000,
    seat: {
      id: 2000,
      seatNumber: 'string',
      isNearEmergencyExit: true,
      isLockedBack: true,
      category: 'FIRST',
      aircraftId: 0,
    },
  },
  {
    id: 20,
    fare: 999,
    isRegistered: true,
    isSold: true,
    isBooked: true,
    flightId: 4003,
    seat: {
      id: 4003,
      seatNumber: 'string',
      isNearEmergencyExit: true,
      isLockedBack: true,
      category: 'BUSINESS',
      aircraftId: 0,
    },
  },
];
