export const testData = [
  {
    id: 1,
    country: 'Россия',
    city: 'Москва',
    gmt: 'GMT +3',
    winterGmt: 'GMT +4',
  },
  {
    id: 2,
    country: 'Афганистан',
    city: 'Кабул',
    gmt: 'GMT +4:30',
    winterGmt: 'GMT +4:30',
  },
  {
    id: 3,
    country: 'Германия',
    city: 'Берлин',
    gmt: 'GMT +1',
    winterGmt: 'GMT +2',
  },
  {
    id: 4,
    country: 'Франция',
    city: 'Париж',
    gmt: 'GMT +1',
    winterGmt: 'GMT +2',
  },
  {
    id: 5,
    country: 'Италия',
    city: 'Рим',
    gmt: 'GMT +1',
    winterGmt: 'GMT +2',
  },
  {
    id: 6,
    country: 'Испания',
    city: 'Мадрид',
    gmt: 'GMT +1',
    winterGmt: 'GMT +2',
  },
  {
    id: 7,
    country: 'Великобритания',
    city: 'Лондон',
    gmt: 'GMT +0',
    winterGmt: 'GMT +1',
  },
  {
    id: 8,
    country: 'США',
    city: 'Нью-Йорк',
    gmt: 'GMT -5',
    winterGmt: 'GMT -4',
  },
  {
    id: 9,
    country: 'США',
    city: 'Лос-Анджелес',
    gmt: 'GMT -8',
    winterGmt: 'GMT -7',
  },
  {
    id: 10,
    country: 'Канада',
    city: 'Торонто',
    gmt: 'GMT -5',
    winterGmt: 'GMT -4',
  },
  {
    id: 11,
    country: 'Япония',
    city: 'Токио',
    gmt: 'GMT +9',
    winterGmt: 'GMT +9',
  },
  {
    id: 12,
    country: 'Китай',
    city: 'Пекин',
    gmt: 'GMT +8',
    winterGmt: 'GMT +8',
  },
  {
    id: 13,
    country: 'Индия',
    city: 'Дели',
    gmt: 'GMT +5:30',
    winterGmt: 'GMT +5:30',
  },
  {
    id: 14,
    country: 'Бразилия',
    city: 'Рио-де-Жанейро',
    gmt: 'GMT -3',
    winterGmt: 'GMT -2',
  },
  {
    id: 15,
    country: 'Австралия',
    city: 'Сидней',
    gmt: 'GMT +10',
    winterGmt: 'GMT +11',
  },
  {
    id: 16,
    country: 'ЮАР',
    city: 'Кейптаун',
    gmt: 'GMT +2',
    winterGmt: 'GMT +2',
  },
  {
    id: 17,
    country: 'Мексика',
    city: 'Мехико',
    gmt: 'GMT -6',
    winterGmt: 'GMT -5',
  },
  {
    id: 18,
    country: 'Аргентина',
    city: 'Буэнос-Айрес',
    gmt: 'GMT -3',
    winterGmt: 'GMT -3',
  },
  {
    id: 19,
    country: 'Турция',
    city: 'Стамбул',
    gmt: 'GMT +3',
    winterGmt: 'GMT +3',
  },
  {
    id: 20,
    country: 'Египет',
    city: 'Каир',
    gmt: 'GMT +2',
    winterGmt: 'GMT +2',
  },
  {
    id: 21,
    country: 'Саудовская Аравия',
    city: 'Эр-Рияд',
    gmt: 'GMT +3',
    winterGmt: 'GMT +3',
  },
  {
    id: 22,
    country: 'ОАЭ',
    city: 'Дубай',
    gmt: 'GMT +4',
    winterGmt: 'GMT +4',
  },
  {
    id: 23,
    country: 'Иран',
    city: 'Тегеран',
    gmt: 'GMT +3:30',
    winterGmt: 'GMT +3:30',
  },
  {
    id: 24,
    country: 'Пакистан',
    city: 'Исламабад',
    gmt: 'GMT +5',
    winterGmt: 'GMT +5',
  },
  {
    id: 25,
    country: 'Индонезия',
    city: 'Джакарта',
    gmt: 'GMT +7',
    winterGmt: 'GMT +7',
  },
  {
    id: 26,
    country: 'Таиланд',
    city: 'Бангкок',
    gmt: 'GMT +7',
    winterGmt: 'GMT +7',
  },
  {
    id: 27,
    country: 'Вьетнам',
    city: 'Ханой',
    gmt: 'GMT +7',
    winterGmt: 'GMT +7',
  },
  {
    id: 28,
    country: 'Южная Корея',
    city: 'Сеул',
    gmt: 'GMT +9',
    winterGmt: 'GMT +9',
  },
  {
    id: 29,
    country: 'Филиппины',
    city: 'Манила',
    gmt: 'GMT +8',
    winterGmt: 'GMT +8',
  },
  {
    id: 30,
    country: 'Малайзия',
    city: 'Куала-Лумпур',
    gmt: 'GMT +8',
    winterGmt: 'GMT +8',
  },
  {
    id: 31,
    country: 'Сингапур',
    city: 'Сингапур',
    gmt: 'GMT +8',
    winterGmt: 'GMT +8',
  },
  {
    id: 32,
    country: 'Новая Зеландия',
    city: 'Окленд',
    gmt: 'GMT +12',
    winterGmt: 'GMT +13',
  },
  {
    id: 33,
    country: 'Чили',
    city: 'Сантьяго',
    gmt: 'GMT -4',
    winterGmt: 'GMT -3',
  },
  {
    id: 34,
    country: 'Колумбия',
    city: 'Богота',
    gmt: 'GMT -5',
    winterGmt: 'GMT -5',
  },
  {
    id: 35,
    country: 'Перу',
    city: 'Лима',
    gmt: 'GMT -5',
    winterGmt: 'GMT -5',
  },
  {
    id: 36,
    country: 'Венесуэла',
    city: 'Каракас',
    gmt: 'GMT -4',
    winterGmt: 'GMT -4',
  },
  {
    id: 37,
    country: 'Куба',
    city: 'Гавана',
    gmt: 'GMT -5',
    winterGmt: 'GMT -4',
  },
  {
    id: 38,
    country: 'Ямайка',
    city: 'Кингстон',
    gmt: 'GMT -5',
    winterGmt: 'GMT -5',
  },
  {
    id: 39,
    country: 'Греция',
    city: 'Афины',
    gmt: 'GMT +2',
    winterGmt: 'GMT +3',
  },
  {
    id: 40,
    country: 'Португалия',
    city: 'Лиссабон',
    gmt: 'GMT +0',
    winterGmt: 'GMT +1',
  },
  {
    id: 41,
    country: 'Швеция',
    city: 'Стокгольм',
    gmt: 'GMT +1',
    winterGmt: 'GMT +2',
  },
  {
    id: 42,
    country: 'Норвегия',
    city: 'Осло',
    gmt: 'GMT +1',
    winterGmt: 'GMT +2',
  },
  {
    id: 43,
    country: 'Финляндия',
    city: 'Хельсинки',
    gmt: 'GMT +2',
    winterGmt: 'GMT +3',
  },
  {
    id: 44,
    country: 'Польша',
    city: 'Варшава',
    gmt: 'GMT +1',
    winterGmt: 'GMT +2',
  },
  {
    id: 45,
    country: 'Украина',
    city: 'Киев',
    gmt: 'GMT +2',
    winterGmt: 'GMT +3',
  },
  {
    id: 46,
    country: 'Беларусь',
    city: 'Минск',
    gmt: 'GMT +3',
    winterGmt: 'GMT +3',
  },
  {
    id: 47,
    country: 'Казахстан',
    city: 'Астана',
    gmt: 'GMT +6',
    winterGmt: 'GMT +6',
  },
  {
    id: 48,
    country: 'Узбекистан',
    city: 'Ташкент',
    gmt: 'GMT +5',
    winterGmt: 'GMT +5',
  },
  {
    id: 49,
    country: 'Туркменистан',
    city: 'Ашхабад',
    gmt: 'GMT +5',
    winterGmt: 'GMT +5',
  },
  {
    id: 50,
    country: 'Киргизия',
    city: 'Бишкек',
    gmt: 'GMT +6',
    winterGmt: 'GMT +6',
  },
];
